services:
  prometheus:
    image: prom/prometheus
    container_name: llm-apm-prometheus
    volumes:
      - ../observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - llm-apm-net

  grafana:
    image: grafana/grafana
    container_name: llm-apm-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - llm-apm-net

  backend:
    container_name: backend
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
    ports:
      - "4000:4000"
    expose:
      - "4000"
    env_file:
      - ../.env
    networks:
      - llm-apm-net

  frontend:
    build:
      context: ../frontend
    ports:
      - "5173:5173"
    env_file:
      - ../.env
    networks:
      - llm-apm-net

networks:
  llm-apm-net:
    driver: bridge